package mcp

import (
	"bytes"
	"context"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/google/uuid"

	"github.com/jbmopper/meristem/internal/buildguard"
	"github.com/jbmopper/meristem/internal/domain"
)

// Legacy byte-compatibility fixtures. The files under testdata/legacy were
// generated by running TestGenerateLegacyGoldens against the BASE commit
// c5a99ac (the pre-2026 server), so TestLegacyGoldenBytes proves the served
// legacy bytes are unchanged rather than asserting selected keys. The one
// reviewed exception is the append-event payload schema correction: all eras
// now declare payload as an object so clients cannot silently double-encode
// authoritative signals. The comparison normalizes exactly that known delta
// while retaining byte-for-byte coverage for everything else.

const legacyGoldenDir = "testdata/legacy"

// newGoldenServer is fully deterministic: fixed identity, fixed build status,
// no dependencies. Both the generator (at base) and the assertion (at head)
// must construct the identical server.
func newGoldenServer(t *testing.T) *Server {
	t.Helper()
	const commit = "cccccccccccccccccccccccccccccccccccccccc"
	s := New(Deps{}, ServerInfo{
		Name:    "meristem-golden",
		Version: "golden",
		BuildStatus: buildguard.ProviderFunc(func() buildguard.Status {
			return buildguard.Status{
				State:            buildguard.StateCurrent,
				CompiledCommit:   commit,
				ExpectedCommit:   commit,
				CompiledMetadata: buildguard.CompiledValid,
				Reason:           "compiled commit matches the reviewed v1 pin",
			}
		}),
	}, nil)
	s.actor = domain.Token{
		ID:     uuid.MustParse("00000000-0000-0000-0000-000000000001"),
		Source: domain.SourceHuman,
		Name:   "golden",
	}
	return s
}

// legacyGoldenRequests covers the complete legacy method surface: initialize
// under both fixture-backed versions, tools/list, a tools/call (unknown tool,
// the deterministic no-database case), ping, and shutdown.
func legacyGoldenRequests() map[string]string {
	return map[string]string{
		"initialize-2025-06-18": `{"jsonrpc":"2.0","id":1,"method":"initialize","params":{"protocolVersion":"2025-06-18"}}`,
		"initialize-2025-11-25": `{"jsonrpc":"2.0","id":1,"method":"initialize","params":{"protocolVersion":"2025-11-25"}}`,
		"tools-list":            `{"jsonrpc":"2.0","id":1,"method":"tools/list"}`,
		"tools-call-unknown":    `{"jsonrpc":"2.0","id":1,"method":"tools/call","params":{"name":"nonexistent.tool"}}`,
		"ping":                  `{"jsonrpc":"2.0","id":1,"method":"ping"}`,
		"shutdown":              `{"jsonrpc":"2.0","id":1,"method":"shutdown"}`,
	}
}

func runGoldenRequest(t *testing.T, req string) string {
	t.Helper()
	s := newGoldenServer(t)
	out := &bytes.Buffer{}
	if err := s.Run(context.Background(), strings.NewReader(req+"\n"), out); err != nil {
		t.Fatalf("Run returned: %v", err)
	}
	return strings.TrimRight(out.String(), "\n")
}

// TestGenerateLegacyGoldens regenerates the fixtures. It is env-gated and
// intended to run against the pre-2026 base commit only; regenerating from a
// post-2026 tree would defeat the point of the byte comparison.
func TestGenerateLegacyGoldens(t *testing.T) {
	outDir := os.Getenv("MERISTEM_GOLDEN_OUT")
	if outDir == "" {
		t.Skip("MERISTEM_GOLDEN_OUT not set; goldens are only regenerated deliberately")
	}
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		t.Fatalf("create golden dir: %v", err)
	}
	for name, req := range legacyGoldenRequests() {
		line := runGoldenRequest(t, req)
		if err := os.WriteFile(filepath.Join(outDir, name+".json"), []byte(line+"\n"), 0o644); err != nil {
			t.Fatalf("write golden %s: %v", name, err)
		}
	}
}

func TestLegacyGoldenBytes(t *testing.T) {
	for name, req := range legacyGoldenRequests() {
		want, err := os.ReadFile(filepath.Join(legacyGoldenDir, name+".json"))
		if err != nil {
			t.Fatalf("read golden %s: %v (generate at the base commit with MERISTEM_GOLDEN_OUT)", name, err)
		}
		got := runGoldenRequest(t, req)
		if name == "tools-list" {
			const corrected = `"payload":{"description":"JSON OBJECT payload describing the event. Must be the object itself - a JSON-encoded string of the object is rejected as double-encoded.","type":"object"}`
			const legacy = `"payload":{"description":"Arbitrary JSON payload describing the event."}`
			if strings.Count(got, corrected) != 1 {
				t.Fatalf("tools-list: reviewed append payload schema correction count = %d, want 1", strings.Count(got, corrected))
			}
			got = strings.Replace(got, corrected, legacy, 1)
		}
		if got != strings.TrimRight(string(want), "\n") {
			t.Errorf("%s: legacy response bytes changed from the c5a99ac golden\n got: %s\nwant: %s", name, got, strings.TrimRight(string(want), "\n"))
		}
	}
}
